name: Solar System Workflow Matrix

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'

env:
  MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
  MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}

jobs:
  unit-testing:
    name: Unit Testing
    strategy:
      matrix:
        nodejs_version: [18, 19, 20]
        operating_system: [ubuntu-latest, macos-latest]
        exclude:
          - nodejs_version: 18
            operating_system: macos-latest
    runs-on: ${{ matrix.operating_system }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup NodeJS Version - ${{ matrix.nodejs_version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.nodejs_version }}

      - name: Cache NPM dependencies
        #https://docs.github.com/en/actions/concepts/workflows-and-actions/dependency-caching
        #https://docs.github.com/en/actions/reference/workflows-and-actions/dependency-caching
        #https://github.com/actions/cache
        uses: actions/cache@v6
        id: npm-cache 
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}
          #whenever the package-lock.json changes, we invalidate the caching
          #in the first run, there will be no cache

      - name: Install Dependencies
        run: npm install

      - name: Unit Testing
        id: nodejs-unit-testing-step #we use this id in future conditions
        run: npm test
      
      - name: Archive Test Result
        #https://docs.github.com/en/actions/reference/workflows-and-actions/contexts#steps-context
        #https://docs.github.com/en/actions/reference/workflows-and-actions/expressions#status-check-functions
        #if: failure() && steps.nodejs-unit-testing-step.outcome == 'failure' || steps.nodejs-unit-testing-step.outcome == 'success'
        #the previous conditions indicates this step to execute when one of the previous steps failed but not to mark the previous step as successful as it happens with the continue-on-error option
        #similarly with always(), the unit testing step can fail 
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: Mocha-Test-Result
          path: test-results.xml

  code-coverage: 
    name: Code Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup NodeJS Version - 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache NPM dependencies
        uses: actions/cache@v6
        id: npm-cache 
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}
          #whenever the package-lock.json changes, we invalidate the caching
          #in the first run, there will be no cache

      - name: Install Dependencies
        run: npm install

      - name: Check Code Coverage
        #https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax#jobsjob_idstepscontinue-on-error
        continue-on-error: true #with this, in case of an error, it still shows successfull
        run: npm run coverage

      - name: Archive Test Result
        uses: actions/upload-artifact@v7
        with:
          name: Code-Coverage-Result
          path: coverage #the coverage folder
          retention-days: 5 #delete the artifact after 5 days